BOT_NAME: "[Dev] Velo Utro Bot"
BOT_USERNAME: "DevVeloutroBot"
STATIC_EVENTS: "🎲 Настолки,🎉 Туса,Другое"
EVENT_TYPES:
  - "🚴‍♀️ Велосипед"
  - "🛶 Активность на воде"
  - "🎲 Настолки"
  - "🚶‍♀️ Прогулка"
  - "🎉 Туса"
  - "Другое"