BOT_NAME: "Velo Morning Orel Bot"
BOT_USERNAME: "VeloMorningBot"
WEBHOOK_DOMAIN: "https://example.com"
STATIC_EVENTS: "๐ถ ะะบัะธะฒะฝะพััั ะฝะฐ ะฒะพะดะต,๐ฒ ะะฐััะพะปะบะธ,๐ ะขััะฐ,ะััะณะพะต"
EVENT_TYPES:
  - "๐ดโโ๏ธ ะะตะปะพัะธะฟะตะด"
  - "๐ถ ะะบัะธะฒะฝะพััั ะฝะฐ ะฒะพะดะต"
  - "๐ฒ ะะฐััะพะปะบะธ"
  - "๐โโ๏ธ ะะตะณ"
  - "๐ถโโ๏ธ ะัะพะณัะปะบะฐ"
  - "๐ ะขััะฐ"
  - "ะััะณะพะต"