BOT_NAME: "[Test] Velo Utro Bot"
BOT_USERNAME: "TestVeloutroBot"
STATIC_EVENTS: "🎲 Настолки,🎉 Туса,❄️ Зимние активности,🎬 Кино,Другое"
EVENT_TYPES:
  - "🚴‍♀️ Велосипед"
  - "🛶 Активность на воде"
  - "🎲 Настолки"
  - "🚶‍♀️ Прогулка"
  - "🎉 Туса"
  - "❄️ Зимние активности"
  - "🎬 Кино"
  - "Другое"
